?node rdf:type saref:Meter .
?node saref:makesMeasurement ?measurement .
?measurement rdf:type saref:Measurement .
?measurement saref:relatesToProperty ?property .
?property rdf:type ?type .
?measurement saref:isMeasuredIn ?unit .
?measurement saref:hasValue ?value .
?value rdf:type xsd:float .
?measurement saref:hasTimestamp ?timestamp .
?timestamp rdf:type time:Instant .